import Link from "next/link"
import { InternalPage, InternalPanel } from "@/components/internal-page"

const artists = [
  { name: "Sandabado", role: "Producer / Composer", pillar: "Studios", icon: "🜄", color: "#2BA8A0", bio: "The first signing. Debut album streaming now. Vinyl pressing available.", latest: "Sandabado (Self-Titled)" },
  { name: "Sarah Veya", role: "Vocalist / Songwriter", pillar: "Studios", icon: "🜄", color: "#2BA8A0", bio: "Currently tracking her debut EP. Voice like water on glass.", latest: "Memory (Single)" },
  { name: "Marcus Reed", role: "Guitarist / Composer", pillar: "Presence", icon: "🜂", color: "#C2542D", bio: "Scoring The Instrument. Solo work in development.", latest: "Spark (Demo)" },
  { name: "Lila Chen", role: "Filmmaker / Visual Director", pillar: "Studios", icon: "🜄", color: "#2BA8A0", bio: "Directing the Glory Peak documentary series. Experimental film roots.", latest: "Ground (Short Film)" },
  { name: "The Hearth", role: "Collective / Sound Healing", pillar: "Guardian", icon: "☉", color: "#C9A227", bio: "Live ceremonial music recorded at Hearthfire Sessions. No playback — only presence.", latest: "Circle (Live Recording)" },
]

export default function RosterPage() {
  return <InternalPage solid="icosahedron" color="43,168,160" lighterBackdrop><section className="px-6 py-16 text-center sm:py-20"><Link href="/pillars/studios" className="font-[family-name:var(--font-mono)] text-xs tracking-[.12em] uppercase text-[var(--ghost)] transition hover:text-[#2BA8A0]">← Back to Studios</Link><span className="mt-8 block text-4xl">🜄</span><h1 className="mt-4 font-[family-name:var(--font-display)] text-5xl text-[var(--bone)]">The Roster</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[var(--ghost)]">Not a label. A waterway. Artists who retain everything. Production, engineering, distribution, and sync — without surrendering ownership.</p></section><section className="px-6 pb-16 sm:pb-20"><div className="mx-auto grid max-w-4xl gap-6 md:grid-cols-2">{artists.map((artist) => <InternalPanel key={artist.name} className="border-[var(--mercury)] bg-[var(--steel)]"><div className="flex items-center gap-3"><span className="text-2xl" style={{ color: artist.color }}>{artist.icon}</span><div><h2 className="font-[family-name:var(--font-display)] text-xl text-[var(--bone)]">{artist.name}</h2><p className="font-[family-name:var(--font-mono)] text-xs text-[var(--ghost)]">{artist.role}</p></div></div><p className="mt-4 text-sm leading-6 text-[var(--ghost)]">{artist.bio}</p><div className="mt-4 border-t border-[var(--mercury)] pt-3 font-[family-name:var(--font-mono)] text-xs"><p className="text-[var(--halo-dim)]">Latest: <span className="text-[var(--bone)]">{artist.latest}</span></p><p className="mt-2" style={{ color: artist.color }}>Pillar: {artist.pillar}</p></div></InternalPanel>)}<InternalPanel className="flex flex-col items-center justify-center border-dashed border-[var(--mercury)] bg-[var(--carbon)] text-center"><span className="text-2xl text-[var(--ghost)]">🜄</span><h2 className="mt-3 font-[family-name:var(--font-display)] text-xl text-[var(--ghost)]">Your Name Here</h2><p className="mt-1 font-[family-name:var(--font-mono)] text-xs text-[var(--halo-dim)]">The next signal</p><p className="mt-4 text-sm leading-6 text-[var(--ghost)]">Submissions are open. If your work carries the frequency, we want to hear it.</p><a href="mailto:studios@wholebody.earth" className="mt-5 font-[family-name:var(--font-mono)] text-xs tracking-[.1em] uppercase text-[#2BA8A0] transition hover:text-[var(--bone)]">Submit Your Work →</a></InternalPanel></div></section></InternalPage>
}
